### ISSUE TITLE
Feature Request: Integrate Touch Joystick

### ISSUE THREAD

**Issue by JoeyHengst** [jwhenry3/game-architecture#1]
First of all thank you for this awesome setup! 

Really enjoying getting my hands dirty with this.

Would love to see an integration of a virtual joystick.

**Comment by jwhenry3** [comment]
I'm glad someone is benefiting from it!

Adding nippleJS should be as simple as writing an adapter to interface with it and exposing events through Subjects/Observables so they can be interacted with like the rest of the app. I'll look into it and try to get something together in due time.

**Comment by JoeyHengst** [comment]
> I'm glad someone is benefiting from it!
> 
> Adding nippleJS should be as simple as writing an adapter to interface with it and exposing events through Subjects/Observables so they can be interacted with like the rest of the app. I'll look into it and try to get something together in due time.

Ah yeah I now did it with an angular wrapper of nipplejs using https://www.npmjs.com/package/ngx-joystick

And used it in the game-engine component. 4 directional movement works sort of if I Don’t hold the joystick while changing direction. It’s more like a d-pad right now ;-) and I am now trying to figure out how to get 8 directional moving  working. 

I want to start an 2d mmo based on snes like sprites “secret of mana” style.

Do you maybe have a solution for the following issue: Since phaser is wrapped in an angular wrapper so when you change something the hotreload kicks in. But I seem to lose the socket connection and it redirects me to the world list and when I then try to login it wouldn’t let me. If then have to clear cache and logout and then relogin again.

Thanks!

**Comment by jwhenry3** [comment]
I'll do some thinking on this. We can track the chosen world and character on the server, and on reconnect try to get the user back to that state. I like this back and forth because it re-sparks my interest in this.

I'll take some time to come up with a re-establishment scenario patch.

I looked briefly at that wrapper too. 

Tie the joystick to a service that can be injected into the multiplayer scene class and used just like the `input.keyboard` events.
I'll work on my own implementation of the library and we can compare notes.

**Comment by jwhenry3** [comment]
Please checkout feature/joystick to see how I approached the joystick implementation

**Comment by jwhenry3** [comment]
I do notice that the directional movement does not respect the user's input after sliding across a plane. I'll investigate that at some point.

**Comment by JoeyHengst** [comment]
> Please checkout feature/joystick to see how I approached the joystick implementation

Awesome. Will take a look asap. I have started to make a microservice for handling parties I am still exploring and figuring out the architecture. Thanks for taking the time! Keep it up 💪

**Comment by jwhenry3** [comment]
I would expect a party microservice to handle some communication events and business logic in regards to exp calculations, etc. Not sure how you plan to build that out

**Comment by JoeyHengst** [comment]
> I would expect a party microservice to handle some user filtering requests.
> 
> Maybe the interface would be like:
> 
> ```
> joinParty(leaderId, selfId)
> leaveParty(leaderId, selfId)
> kick(leaderId, targetId)
> getMembers(): (id|name|model)[]
> ```

Awesome work with joystick. Needs some smoother movement overall but so far very nice. Yeah I made an example party service in my fork the interface is somewhat you describe. Still heavily in progress though ;)

**Comment by jwhenry3** [comment]
I like the direction you're taking with the party microservice, keep it up!

**Comment by jwhenry3** [comment]
NippleJS through ngx-joystick is now in develop
